// AUTO-GENERATED by scripts/compute-head-anchors.mjs — do not edit by hand.
// Per-creature head anchor (fractions of the square sprite frame): where the
// head dome starts (top), its horizontal centre (cx) and width (w). Used to pin
// worn accessories onto the actual head of each form.
export interface HeadAnchor { top: number; cx: number; w: number; }
export const HEAD_ANCHORS: Record<string, HeadAnchor> = {
  "cell": {
    "top": 0.3661,
    "cx": 0.4911,
    "w": 0.4375
  },
  "aquara": {
    "top": 0.2917,
    "cx": 0.497,
    "w": 0.4048
  },
  "bloomkin": {
    "top": 0.3224,
    "cx": 0.4967,
    "w": 0.3684
  },
  "bramble": {
    "top": 0.288,
    "cx": 0.4918,
    "w": 0.4457
  },
  "cirrus": {
    "top": 0.2849,
    "cx": 0.4971,
    "w": 0.4419
  },
  "dewdrop": {
    "top": 0.3333,
    "cx": 0.4907,
    "w": 0.4167
  },
  "dewling": {
    "top": 0.2917,
    "cx": 0.4965,
    "w": 0.3333
  },
  "faerie": {
    "top": 0.3,
    "cx": 0.4972,
    "w": 0.4778
  },
  "fernix": {
    "top": 0.2656,
    "cx": 0.4974,
    "w": 0.474
  },
  "floofa": {
    "top": 0.314,
    "cx": 0.4971,
    "w": 0.4419
  },
  "grym": {
    "top": 0.2733,
    "cx": 0.4971,
    "w": 0.3721
  },
  "leafling": {
    "top": 0.2639,
    "cx": 0.4931,
    "w": 0.4236
  },
  "mirok": {
    "top": 0.2558,
    "cx": 0.4971,
    "w": 0.3953
  },
  "murkling": {
    "top": 0.2571,
    "cx": 0.4964,
    "w": 0.4286
  },
  "petala": {
    "top": 0.2667,
    "cx": 0.4944,
    "w": 0.3722
  },
  "plip": {
    "top": 0.2988,
    "cx": 0.497,
    "w": 0.4512
  },
  "pomkin": {
    "top": 0.3314,
    "cx": 0.4971,
    "w": 0.3953
  },
  "pompom": {
    "top": 0.3214,
    "cx": 0.4964,
    "w": 0.4429
  },
  "puddle": {
    "top": 0.2647,
    "cx": 0.4926,
    "w": 0.4559
  },
  "puff": {
    "top": 0.2778,
    "cx": 0.4907,
    "w": 0.4537
  },
  "puffling": {
    "top": 0.2635,
    "cx": 0.4966,
    "w": 0.3919
  },
  "seraph": {
    "top": 0.3278,
    "cx": 0.4972,
    "w": 0.4444
  },
  "sludge": {
    "top": 0.2798,
    "cx": 0.497,
    "w": 0.4048
  },
  "snarl": {
    "top": 0.2791,
    "cx": 0.4971,
    "w": 0.3488
  },
  "splasha": {
    "top": 0.2733,
    "cx": 0.4913,
    "w": 0.3663
  },
  "sprig": {
    "top": 0.2679,
    "cx": 0.497,
    "w": 0.369
  },
  "sprout": {
    "top": 0.2679,
    "cx": 0.4911,
    "w": 0.3839
  },
  "thorne": {
    "top": 0.2722,
    "cx": 0.4917,
    "w": 0.4778
  },
  "tidus": {
    "top": 0.3214,
    "cx": 0.497,
    "w": 0.3929
  },
  "tuftling": {
    "top": 0.2639,
    "cx": 0.4965,
    "w": 0.375
  },
  "weedling": {
    "top": 0.2885,
    "cx": 0.5096,
    "w": 0.3782
  },
  "kiwi/baby": {
    "top": 0.3387,
    "cx": 0.4919,
    "w": 0.4113
  },
  "kiwi/legendary": {
    "top": 0.2845,
    "cx": 0.4914,
    "w": 0.4914
  },
  "kiwi/teen": {
    "top": 0.2845,
    "cx": 0.4914,
    "w": 0.4914
  },
  "mochi/baby": {
    "top": 0.3214,
    "cx": 0.4955,
    "w": 0.4286
  },
  "mochi/legendary": {
    "top": 0.2586,
    "cx": 0.5086,
    "w": 0.4052
  },
  "mochi/teen": {
    "top": 0.2586,
    "cx": 0.5086,
    "w": 0.4052
  },
  "nori/baby": {
    "top": 0.3387,
    "cx": 0.4919,
    "w": 0.4919
  },
  "nori/legendary": {
    "top": 0.2845,
    "cx": 0.4871,
    "w": 0.3793
  },
  "nori/teen": {
    "top": 0.2845,
    "cx": 0.4871,
    "w": 0.3793
  },
  "pao/baby": {
    "top": 0.25,
    "cx": 0.4828,
    "w": 0.4397
  },
  "pao/legendary": {
    "top": 0.2917,
    "cx": 0.4875,
    "w": 0.4167
  },
  "pao/teen": {
    "top": 0.2917,
    "cx": 0.4875,
    "w": 0.4167
  },
  "yuki/baby": {
    "top": 0.2823,
    "cx": 0.496,
    "w": 0.4274
  },
  "yuki/legendary": {
    "top": 0.2768,
    "cx": 0.4866,
    "w": 0.3929
  },
  "yuki/teen": {
    "top": 0.2768,
    "cx": 0.4866,
    "w": 0.3929
  }
};
export const DEFAULT_HEAD_ANCHOR: HeadAnchor = { top: 0.28, cx: 0.5, w: 0.44 };
/** accessory image aspect ratio = height / width (of the padded square file) */
export const ITEM_ASPECT: Record<string, number> = {
  "apple": 1,
  "back": 1,
  "ball": 1,
  "blanket": 1,
  "bow": 1,
  "bowtie": 1,
  "cake": 1,
  "cap": 1,
  "cat_ears": 1,
  "chart": 1,
  "coin": 1,
  "crown": 1,
  "devil_horns": 1,
  "fish": 1,
  "flower": 1,
  "flower_crown": 1,
  "gear": 1,
  "glasses": 1,
  "halo": 1,
  "headphones": 1,
  "heart_glasses": 1,
  "party_hat": 1,
  "scarf": 1,
  "shop": 1,
  "star_toy": 1,
  "sunglasses": 1,
  "tiara": 1,
  "top_hat": 1,
  "wizard_hat": 1
};
/**
 * Tight content box of each accessory within its padded square PNG, as fractions
 * of the file. Lets the overlay be placed by the VISIBLE art (no float, correct
 * size) instead of the transparent padding. fa=file aspect, w=content width,
 * cx/cy=content centre, bottom=content bottom edge.
 */
export interface ItemBox { fa: number; w: number; cx: number; cy: number; bottom: number; }
export const ITEM_BOX: Record<string, ItemBox> = {
  "apple": {
    "fa": 1,
    "w": 0.7771,
    "cx": 0.4968,
    "cy": 0.5,
    "bottom": 0.9299
  },
  "back": {
    "fa": 1,
    "w": 0.8571,
    "cx": 0.5,
    "cy": 0.5,
    "bottom": 0.8482
  },
  "ball": {
    "fa": 1,
    "w": 0.8649,
    "cx": 0.5,
    "cy": 0.4977,
    "bottom": 0.9279
  },
  "blanket": {
    "fa": 1,
    "w": 0.7857,
    "cx": 0.5,
    "cy": 0.5,
    "bottom": 0.9286
  },
  "bow": {
    "fa": 1,
    "w": 0.8592,
    "cx": 0.5,
    "cy": 0.5,
    "bottom": 0.8521
  },
  "bowtie": {
    "fa": 1,
    "w": 0.8667,
    "cx": 0.5,
    "cy": 0.5,
    "bottom": 0.7333
  },
  "cake": {
    "fa": 1,
    "w": 0.68,
    "cx": 0.5,
    "cy": 0.5,
    "bottom": 0.9333
  },
  "cap": {
    "fa": 1,
    "w": 0.8529,
    "cx": 0.5,
    "cy": 0.4926,
    "bottom": 0.8088
  },
  "cat_ears": {
    "fa": 1,
    "w": 0.8667,
    "cx": 0.5,
    "cy": 0.4917,
    "bottom": 0.85
  },
  "chart": {
    "fa": 1,
    "w": 0.7273,
    "cx": 0.4965,
    "cy": 0.5,
    "bottom": 0.9301
  },
  "coin": {
    "fa": 1,
    "w": 0.8571,
    "cx": 0.5,
    "cy": 0.5,
    "bottom": 0.9286
  },
  "crown": {
    "fa": 1,
    "w": 0.8571,
    "cx": 0.5,
    "cy": 0.5,
    "bottom": 0.8304
  },
  "devil_horns": {
    "fa": 1,
    "w": 0.8592,
    "cx": 0.5,
    "cy": 0.5,
    "bottom": 0.7606
  },
  "fish": {
    "fa": 1,
    "w": 0.8571,
    "cx": 0.5,
    "cy": 0.5,
    "bottom": 0.7679
  },
  "flower": {
    "fa": 1,
    "w": 0.7846,
    "cx": 0.5,
    "cy": 0.5,
    "bottom": 0.9308
  },
  "flower_crown": {
    "fa": 1,
    "w": 0.8571,
    "cx": 0.5,
    "cy": 0.4929,
    "bottom": 0.7714
  },
  "gear": {
    "fa": 1,
    "w": 0.8632,
    "cx": 0.5,
    "cy": 0.5,
    "bottom": 0.9316
  },
  "glasses": {
    "fa": 1,
    "w": 0.8571,
    "cx": 0.5,
    "cy": 0.5,
    "bottom": 0.7286
  },
  "halo": {
    "fa": 1,
    "w": 0.8667,
    "cx": 0.5,
    "cy": 0.4917,
    "bottom": 0.7833
  },
  "headphones": {
    "fa": 1,
    "w": 0.8571,
    "cx": 0.4921,
    "cy": 0.5,
    "bottom": 0.9365
  },
  "heart_glasses": {
    "fa": 1,
    "w": 0.8592,
    "cx": 0.5,
    "cy": 0.5,
    "bottom": 0.7183
  },
  "party_hat": {
    "fa": 1,
    "w": 0.6232,
    "cx": 0.5,
    "cy": 0.5,
    "bottom": 0.9275
  },
  "scarf": {
    "fa": 1,
    "w": 0.7164,
    "cx": 0.4925,
    "cy": 0.5,
    "bottom": 0.9254
  },
  "shop": {
    "fa": 1,
    "w": 0.8632,
    "cx": 0.5,
    "cy": 0.5,
    "bottom": 0.8947
  },
  "star_toy": {
    "fa": 1,
    "w": 0.8689,
    "cx": 0.5,
    "cy": 0.5,
    "bottom": 0.8279
  },
  "sunglasses": {
    "fa": 1,
    "w": 0.8571,
    "cx": 0.5,
    "cy": 0.4929,
    "bottom": 0.7143
  },
  "tiara": {
    "fa": 1,
    "w": 0.8571,
    "cx": 0.5,
    "cy": 0.5,
    "bottom": 0.7679
  },
  "top_hat": {
    "fa": 1,
    "w": 0.8519,
    "cx": 0.5,
    "cy": 0.5,
    "bottom": 0.9074
  },
  "wizard_hat": {
    "fa": 1,
    "w": 0.8571,
    "cx": 0.5,
    "cy": 0.5,
    "bottom": 0.8571
  }
};
export const DEFAULT_ITEM_BOX: ItemBox = { fa: 1, w: 0.86, cx: 0.5, cy: 0.5, bottom: 0.93 };
